#Database
POSTGRES_SQL_USERNAME: postgres
POSTGRES_SQL_PASSWORD: letmein
POSTGRES_SQL_HOST: localhost
POSTGRES_SQL_PORT: 5432
POSTGRES_SQL_DB: emailservicedb

#Server
SERVER_PORT: 8085
ACTIVE_PROFILE: dev